# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '43959'
      rtd_project_name: 'airship-specs'

    post:
      jobs:
        - specs-upload-git-mirror

- job:
    name: specs-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/specs to airshipit/specs
    vars:
      git_mirror_repository: airshipit/specs
    secrets:
      - name: git_mirror_credentials
        secret: specs-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: specs-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - MOAk3/3afGYzkiH0XfGRMzkWbQN7iznR48dM1oe/Pf+OqvBcKKS87o7E1zWXwU+jyaC1q
          EqIs2TVw0KJwhEcRjPq7nu8JaXFqACfW1ll79buruVy5rW+MGrRTa9Vyh4euygyb3tZ2B
          Oo0zFh9bOzkHGKLa5wossscFOSgfFiwuar7A4B9yNohux+KAgtrOOXjyhfJjvodLasdg9
          xIE6Gy5uZ4KW3dhIfgZGLzLRNFtmwJs5C4J7306Cz1dzSuSM+IpTkmO4DnYsFN8GaBQE0
          R1EuhmrWHntGKDZQSn+hCTcvmexa1iK25u/38QgY0wv8DSV2PrtOatdx0oV1sxp29yXkX
          LeMmmtLvm/Z0v4NI+2kFoOJ4Ww5CJFEU1ePmgw5vCPQ8gTskc4yXyx5MBhpL+0rhK0Kdj
          v++TAukeDG3wGAYm+uiy+f9V0VWcf7R2vJv0y1gomZ0kKEadY1pZ+eCYfqhu2e+3j0/fL
          tSp1DK+B71CnwRs2S7UcYXb0KStbR09IcrDKiq/qn1rwrdFvOVdU6o0HRVuJiaXGOy32Y
          qKF7PlWWDEFAO/Nkcq30qz46a9eZ0qP9+f4+FvqMxWdSVpKNVlRlkGj6deQ+R7Kcd52/y
          ZOkfkqzra8gkbUAh5HUg1KgomyaL9UxkbI6/qKLYkWlq1eAxIZnTj+lRlwC8MU=
        - RMcmXLTFvCeHQRrvGCzSIEaSb6khIMnR/05ldEdpC5D3KVDlNrAy97IHPUX1T71jO4a7C
          FPF/zLYG6y75nt1085ePOI962IDrEjgaJTF6fhUAgjDGRhRXRBmKYMXIOKTUPISXWRmj6
          eaRCjJO3LCVzbQhPh7aapI1KkYNooPeAXTQKa3fD/UHgCnczoAOIqt4hDD/LWyTw0g++O
          1H65roddGAMiZ9pPHPVuPlo9xEcpRhy7m1f4H/T226Vq9O40MoAAfo/ZHK/9w+bUqPGwb
          S0mldDoquk//ZMYplt4me5HnO8+OyvfQ2uWtbWps2sX9T6hJ42eoYcvdjEKnpwUvWiiNK
          ndAzaCSENHiSgBB0TDPqRdjK/t9fEWnyC7qmRP1UKg0XPGQpa35ZOc7TLz0bkxNQl5IiK
          gEqOqCekuqgAgT6MooeuARd6MzLInXJmSMWkWHfOvmo5vdVomNv5st7I+iaQZ7BfG97DY
          tJQCKV8Ew0JPQXouOAe/zS+wb3Y78oMD9sBgxVX/vwaKD/Q6YSZWl4F3EpiJfK17eFk+v
          LPUDFp9MpUx9LwTYY05zOk1M4DBBF4KgxGG/dhYOZI2SUt1+HowRHb4y0BqV1Gv54D39+
          Pf106L74iUap4yKpyhO22npJ+HZirtV75GIogCBlUjv+6+iJoHmjuELqK5Buo4=
        - c8HZ5935Akfn5yK5e01Qxmces68XMKJ/pHhoF3R9Lxauo5McnCEy/Ww349WctUFh87LbH
          o9Rgl/xKqXZ+inuvpU8XIxNGLx9kyJGGUfb9Xp7CYU2zQMPl97Y96tWIc4jfcg/J+cOb/
          8I3RhEmN9VZtdMfBJby+cqKKykP9t5n4YD5Ff0OvYXrSG8khCh0F28GkDWaAftG2Wj/Iq
          3/GeEXQMJi+KunuJiZQ1m1+9WUOenpECrnMf7zEDzj+Qtvv/WiRrE8JV1S9pQQ/e8hRMk
          GdJGWVTHmlPtIfeT/AVG68rHP0O/vYUF/xmfFOhk0Zuk1RWgmnIPscn9O1QJPIU7/e4re
          A8NEmE8rlF19BHOc/E7JLotjMUliXaaD+TJHZxdRb3guBRfU2WhzOhkE/0cClXRbcuWyY
          /xn5fgm9APs05UIXRw+P56OMXoVdz6Q4IchdgCVovFnCf42O9FQ8DLTQDRSDcsfXlfjl0
          5fDxzf9MHOQbdGFZsCNcR3jMdxwWKa/WQC5kPyFwoRh1/ndVe23tLupW79zcmSbLfgfQe
          AhJRIUxHAMRpN05DjZbJeHZER1aa1ld+Wp90P1GUBJjiDiW1ePdGtZ1BgskUDWg6Rh1ea
          MimqflpVBcRaVFqvTbKPQVOx375wm8gjKsBvbiG1FO3HZeBG8touSZJ4KxRCto=
        - reOdv29lxqyxNRK60lAP3pgjbDZebaTz8sQnGTKPYml2/SPQdbnSFYqKUkmstzR9I8Qvl
          M5to3JndipR7A7h28kW5+y4yFdiSSmjN6J+eTtDnmCPXXHew3OkPlsOMF6+2qsX4YBGCq
          P0CzjTltuLjydsMiUi4Dv835Ou/SRR/xri9lCATElaP5YdTBmkLBvoi0SsvFATfp2VTTk
          UKaWVoTMzkpFmP6da6ic+YU3Axsd4dybOZzlN0tc20QOTBot0qADw7xK1JVRO84TzcH18
          cH+P6nOmAVRvdjYy32h7WXWwVLY56/AG6eHhH5jh8mHfXZCLH1OUn0ABuI+FRbn0twn5E
          iuJ4vKOmqhMtmWcpqJf2+KBAVjXl7rcor808TXCTmjseKnqTAsWfCJ5aHMvbM7ZAV6Eug
          vXdCLYxSHiVzgXPv4CziNp2ngQgEpoKEgJJTWexWX5XQKFooMSV2vDLcq09Z/cC4Knv4B
          +tkmzPDXtCE/+Fee8eJ7/KbCExbJkGYtlC2uH/dmm+hXZs2kL9U9+2uEnJegRFU2RVX5O
          FHBuZ0iTR+M9HDs9+AAOgau9JJDyb0tGceF85s6a//6yqtWy0nnwhr0ufm1Vkhn2xecKo
          UB/HDjuzIYazupSK00ghb4QZBW4vB6Utr4QRd/cIkqW2Nwj0UORdbs8S0X6fLM=
