- project:
    check:
      jobs:
        - airship-specs-doc-build

    gate:
      jobs:
        - airship-specs-doc-build

    post:
      jobs:
        - airship-specs-doc-publish

- nodeset:
    name: airship-specs-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: airship-specs-doc-build
    description: |
      Build documents locally to validate functionality
    run: gate/playbooks/doc-build.yaml
    timeout: 900
    nodeset: airship-specs-single-node

- job:
    name: airship-specs-doc-publish
    description: |
      Publish documentation on airship-specs.readthedocs.io
    run: gate/playbooks/doc-publish.yaml
    secrets:
      - airship_specs_readthedocs
    timeout: 300
    nodeset: airship-specs-single-node

- secret:
    name: airship_specs_readthedocs
    data:
      url: !encrypted/pkcs1-oaep
        - THj6TIhcV42OhTsG1mA59bUbeKNd/64KCt2Bnqh8D+Fjr2VbaojqHT51/UhuRf+y4BKDi
          Hlaf0kNUS0X4VB5QanDh/mKlU/GhMIyUBCD1PlzMxiefcVl04F+Z0GKlPXJ+qzKYRYK6F
          2i4m8PeCGa8otqUiiqznY0US5Rb0++dEZ6ipuFuaLDl7mmV4MqWuPVJdpBuYqsH/OP6Hd
          VPvSw68Arbqo7n/hriCoI5ZVx9Xk8xhfSTCkUDjhEaHEr+ECTPZLxqmArPEi+gGwEqiLa
          LWwftEeDc2OaSL0X8XlAcCGFYJeLRp5uCTIOh2T0HuIgZxPJ1aHyvvyd3ieyw+ndx27og
          DYPf3/svoYWBaDkQpFQpYFWIwMnzKiZp5giOb2XIr3co43gu/nT49UZJSkc2MPtWMArRb
          CHkj7/MF+lHEDlCEGC+x0u+B1t1Qn++JWVXMDEhHm+KUJ83Q0QSUC1ImJgKgDHWeGAMK/
          6OABOer4D6qG88PHaoSmiKrX7o9tjiuPkVfZYrKjgQSXRj8Iv1GSHdQCjcit/HNFx75Lu
          yPmkFA5XzGXAHNpt33ktib5/ZVzYdFV7lFoNDxs2cDb+qJvD1zAL8rDgwOk7cjv1qWHR+
          1VgnGBiWamD0SRCMY0beTjWQpouius5mfI+d+LPlNr8i1okic6sd2vhG93HMpw=
      token: !encrypted/pkcs1-oaep
        - ZYf6430ZTYgnN3HnbFMUqb0Q8iQWmhpns1UutcWuhOjDYBT7NBvmjJRoAzKTL4JI9qpbm
          EIL2BwpmSGRmJauzJKaTxTitRTGkLZB9nBsBjKw3tu/ga1Mz18IWfKoJWFfhs+omd/YgZ
          DX1nf8I+2Dmmee+lbGfkd8Km39hXRVEkDdT/9fRH7w0JJullf/LHJlQs+mQuGxj4S6lQ0
          GINVneKZKj7EOsoOQexGLDnOjrLDyfUHJiPRTZsg4VTDng/yRb9jJfbph5aTX1QRA2ldp
          VsO4PZhYOiR30SYcNbUELhA/ZKXYeUWrG4hsI8oeO4dCU5cLPMFkh8i+6fvHRjPvPohOl
          fj5xNHbz/wHOHlFFLYX2fs2WCRKdX7g8m/nxiN5ofttNq+k99Is5r30iMUXGzoIG8viSb
          dOcHRXRrFnIa5ZUD4g3QgGnayxXxK9tJqCrW1N9MwfFOIb1kgRCvrGDaho9cOcFshQPTP
          UfsGHncnV87elimGN/tYf8oAU5FWIzzh8xF/kT1e8mVxGrF4BfBV2/Iy26M0MlbeFqMXY
          oWgYCTt57yMhrhdqqRrrYsa/5C5rTv6J+cpPv+VtRo6AQm6KLwBl5sLNuCiBZigKDdwwn
          F/MZZpDi9gkGouoDm6lR+Kje5zpWvdUwJC2TfLst1qFk23FqshAGuOBI9tTRws=
